# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HarborTouch Inventory' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MagicalRecord'
  pod 'Alamofire', '~> 3.4'

  # Pods for HarborTouch Inventory

  target 'HarborTouch InventoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HarborTouch InventoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
